version: 0.1

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo $CODEBUILD_SRC_DIR
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run prod
  post_build:
    commands:
      - mkdir -p build
      - tar jcf build/codebuddah.tar.bz2 ./dist/*
      - echo Build completed on $(date)
artifacts:
  files:
    - build*/**
  discard-paths: yes
