version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo $CODEBUILD_SRC_DIR
      - apt-get update
      - apt-get install -y awscli
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - apt-get install -y nodejs
      - echo $(node -v)
      - npm config set loglevel error
      - npm i -g npm@latest --silent
  build:
    commands:
      - echo Build started on $(date)
      - npm i
      - npm run prod
  post_build:
    commands:
      - cd dist
      - aws s3 sync . s3://codebuddha.io/