version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - apt-get update
      - apt-get install -y awscli
      - npm config set loglevel error
      - PROJECT_VERSION=v$(node -e "console.log( require( './package.json' ).version );")
      - echo "{\"passing\":false,\"project_version\":\"$PROJECT_VERSION\"}" | tee build_status.json
      - aws s3 mv ./build_status.json s3://codebuddha.io/build_status.json
      - aws s3 mv ./status.json s3://codebuddha.io/status.json
      - npm i -g npm@latest --silent
  build:
    commands:
      - echo Build started on $(date)
      - npm i
      - npm run prod
  post_build:
    commands:
      - aws s3 sync ./dist/ s3://codebuddha.io/
      - PROJECT_VERSION=v$(node -e "console.log( require( './package.json' ).version );")
      - echo "{\"passing\":true,\"project_version\":\"$PROJECT_VERSION\"}" | tee build_status.json
      - aws s3 mv ./build_status.json s3://codebuddha.io/build_status.json
  finalizing:
  	commands:
  	  - echo FINALIZING at $(date)