version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - apt-get update
      - apt-get install -y awscli
      - npm config set loglevel error
      - echo "{\"node_version\":\"$(node -v)\",\"npm_version\":\"v$(npm -v)\",\"passing\":failed}" | tee status.json
      - aws s3 mv ./status.json s3://codebuddha.io/status.json
      - npm i -g npm@latest --silent
  build:
    commands:
      - echo Build started on $(date)
      - npm i
      - npm run prod
  post_build:
    commands:
      - cd dist
      - aws s3 sync . s3://codebuddha.io/
      - echo "{\"node_version\":\"$(node -v)\",\"npm_version\":\"v$(npm -v)\",\"passing\":true}" | tee status.json
      - aws s3 mv ./status.json s3://codebuddha.io/status.json